server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&charset=utf8mb4&serverTimezone=UTC
    username: DbAdmin
    password: 123123
  jpa:
    hibernate:
      naming:
        physical-strategy: net.test.dao.CustomNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  jackson:
    serialization:
      indent-output: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

demo:
  email:
    smtp:192.168.254.51
    port:25

